services:
  swu-organizer:
    build: .
    container_name: swu-organizer
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swu-organizer.entrypoints=websecure"
      - "traefik.http.routers.swu-organizer.rule=Host(`swu.mattyflix.com`)"
      - "traefik.http.services.swu-organizer.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
